/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiMatchingRouteImport } from './routes/ai-matching'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CreateParcelRouteImport } from './routes/create-parcel'
import { Route as CreateShipmentRouteImport } from './routes/create-shipment'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as DriverMatchingRouteImport } from './routes/driver-matching'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as SenderRouteImport } from './routes/sender'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as TrackingRouteImport } from './routes/tracking'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMatchingRoute = AiMatchingRouteImport.update({
  id: '/ai-matching',
  path: '/ai-matching',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateParcelRoute = CreateParcelRouteImport.update({
  id: '/create-parcel',
  path: '/create-parcel',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateShipmentRoute = CreateShipmentRouteImport.update({
  id: '/create-shipment',
  path: '/create-shipment',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverMatchingRoute = DriverMatchingRouteImport.update({
  id: '/driver-matching',
  path: '/driver-matching',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const SenderRoute = SenderRouteImport.update({
  id: '/sender',
  path: '/sender',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-matching': typeof AiMatchingRoute
  '/auth': typeof AuthRoute
  '/create-parcel': typeof CreateParcelRoute
  '/create-shipment': typeof CreateShipmentRoute
  '/driver': typeof DriverRoute
  '/driver-matching': typeof DriverMatchingRoute
  '/how-it-works': typeof HowItWorksRoute
  '/marketplace': typeof MarketplaceRoute
  '/sender': typeof SenderRoute
  '/sustainability': typeof SustainabilityRoute
  '/tracking': typeof TrackingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-matching': typeof AiMatchingRoute
  '/auth': typeof AuthRoute
  '/create-parcel': typeof CreateParcelRoute
  '/create-shipment': typeof CreateShipmentRoute
  '/driver': typeof DriverRoute
  '/driver-matching': typeof DriverMatchingRoute
  '/how-it-works': typeof HowItWorksRoute
  '/marketplace': typeof MarketplaceRoute
  '/sender': typeof SenderRoute
  '/sustainability': typeof SustainabilityRoute
  '/tracking': typeof TrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-matching': typeof AiMatchingRoute
  '/auth': typeof AuthRoute
  '/create-parcel': typeof CreateParcelRoute
  '/create-shipment': typeof CreateShipmentRoute
  '/driver': typeof DriverRoute
  '/driver-matching': typeof DriverMatchingRoute
  '/how-it-works': typeof HowItWorksRoute
  '/marketplace': typeof MarketplaceRoute
  '/sender': typeof SenderRoute
  '/sustainability': typeof SustainabilityRoute
  '/tracking': typeof TrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-matching'
    | '/auth'
    | '/create-parcel'
    | '/create-shipment'
    | '/driver'
    | '/driver-matching'
    | '/how-it-works'
    | '/marketplace'
    | '/sender'
    | '/sustainability'
    | '/tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-matching'
    | '/auth'
    | '/create-parcel'
    | '/create-shipment'
    | '/driver'
    | '/driver-matching'
    | '/how-it-works'
    | '/marketplace'
    | '/sender'
    | '/sustainability'
    | '/tracking'
  id:
    | '__root__'
    | '/'
    | '/ai-matching'
    | '/auth'
    | '/create-parcel'
    | '/create-shipment'
    | '/driver'
    | '/driver-matching'
    | '/how-it-works'
    | '/marketplace'
    | '/sender'
    | '/sustainability'
    | '/tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiMatchingRoute: typeof AiMatchingRoute
  AuthRoute: typeof AuthRoute
  CreateParcelRoute: typeof CreateParcelRoute
  CreateShipmentRoute: typeof CreateShipmentRoute
  DriverRoute: typeof DriverRoute
  DriverMatchingRoute: typeof DriverMatchingRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MarketplaceRoute: typeof MarketplaceRoute
  SenderRoute: typeof SenderRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TrackingRoute: typeof TrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-matching': {
      id: '/ai-matching'
      path: '/ai-matching'
      fullPath: '/ai-matching'
      preLoaderRoute: typeof AiMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-parcel': {
      id: '/create-parcel'
      path: '/create-parcel'
      fullPath: '/create-parcel'
      preLoaderRoute: typeof CreateParcelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-shipment': {
      id: '/create-shipment'
      path: '/create-shipment'
      fullPath: '/create-shipment'
      preLoaderRoute: typeof CreateShipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-matching': {
      id: '/driver-matching'
      path: '/driver-matching'
      fullPath: '/driver-matching'
      preLoaderRoute: typeof DriverMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sender': {
      id: '/sender'
      path: '/sender'
      fullPath: '/sender'
      preLoaderRoute: typeof SenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiMatchingRoute: AiMatchingRoute,
  AuthRoute: AuthRoute,
  CreateParcelRoute: CreateParcelRoute,
  CreateShipmentRoute: CreateShipmentRoute,
  DriverRoute: DriverRoute,
  DriverMatchingRoute: DriverMatchingRoute,
  HowItWorksRoute: HowItWorksRoute,
  MarketplaceRoute: MarketplaceRoute,
  SenderRoute: SenderRoute,
  SustainabilityRoute: SustainabilityRoute,
  TrackingRoute: TrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
